FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT python3 app.py

# CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "app:app"]